version: '3.8'

services:

  app:
    build: 
      context: ./node      # Defina o diretório onde está o Dockerfile
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/usr/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    # Comando para instalar dependências e iniciar o app
    command: bash -c "npm install && node index.js"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - node-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  node-network:
    driver: bridge
